/*
 * makeglyphs - make ASM glyph arrays from the VGA font
 *
 * Copyright (C) 2015 Benjamin Gilbert
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>
#include "font.h"

#define COLOR_BITS 2
#define COLORS 3
#define HEIGHT 8
#define GLYPH_BYTES (COLOR_BITS * HEIGHT)
#define TEXT_START 0x20
#define TEXT_END 0x7f

// CHR ROM glyph offsets
#define BACKGROUND_SPECIAL_START 16
#define BACKGROUND_TEXT_START 32
#define SPRITE_TEXT_START 128

const uint8_t sprites[] = {
    0,		// empty space
    1,		// smiley face
    3,		// heart
};
const uint8_t background[] = {
    218,	// top-left corner
    191,	// top-right corner
    192,	// bottom-left corner
    217,	// bottom-right corner
    196,	// horizontal line
    179,	// vertical line
};

static void write_glyph(int codepoint) {
    int row;

    printf("\t.byte ");
    for (row = 0; row < HEIGHT; row++) {
        printf("%s%d", row ? ", " : "", vgafont8[HEIGHT * codepoint + row]);
    }
    printf("\n");
}

static void make_glyphs(void) {
    int i;

    printf("; Autogenerated by makeglyphs\n");

    printf("\nglyphs_sprite\n");
    for (i = 0; i < sizeof(sprites); i++) {
        write_glyph(sprites[i]);
    }
    printf("num_glyphs_sprite = %d\n", sizeof(sprites));

    printf("\nglyphs_background\n");
    for (i = 0; i < sizeof(background); i++) {
        write_glyph(background[i]);
    }
    printf("num_glyphs_background = %d\n", sizeof(background));

    printf("\nglyphs_text\n");
    for (i = TEXT_START; i < TEXT_END; i++) {
        write_glyph(i);
    }
    printf("num_glyphs_text = %d\n", TEXT_END - TEXT_START);
}

static void write_sprite_glyph(int codepoint, int color) {
    int shift;

    printf("\t; codepoint %d\n", codepoint);
    for (shift = 0; shift < COLOR_BITS; shift++) {
        if (color & (1 << shift)) {
            write_glyph(codepoint);
        } else {
            printf("\t.fill %d, 0\n", HEIGHT);
        }
    }
}

static void write_background_glyph(int codepoint) {
    printf("\t; codepoint %d\n", codepoint);
    write_glyph(codepoint);
    printf("\t.fill %d, $ff\n", HEIGHT);
}

static void write_fill(int num_glyphs) {
    assert(num_glyphs >= 0);
    printf("\t; fill %d glyph%s\n", num_glyphs, num_glyphs == 1 ? "" : "s");
    printf("\t.fill %d, 0\n", GLYPH_BYTES * num_glyphs);
}

static void make_chr_rom(void) {
    int i;

    printf("; Autogenerated by makeglyphs\n");

    printf("\n; sprite special glyphs\n");
    for (i = 0; i < sizeof(sprites); i++) {
        write_sprite_glyph(sprites[i], (i % COLORS) + 1);
    }
    write_fill(BACKGROUND_SPECIAL_START - i);

    printf("\n; background special glyphs\n");
    for (i = 0; i < sizeof(background); i++) {
        write_background_glyph(background[i]);
    }
    write_fill(BACKGROUND_TEXT_START - BACKGROUND_SPECIAL_START - i);

    printf("\n; background text glyphs\n");
    for (i = TEXT_START; i < TEXT_END; i++) {
        write_background_glyph(i);
    }
    write_fill(SPRITE_TEXT_START - BACKGROUND_TEXT_START -
            (TEXT_END - TEXT_START));

    printf("\n; sprite text glyphs\n");
    for (i = TEXT_START; i < TEXT_END; i++) {
        write_sprite_glyph(i, ((i - TEXT_START) % COLORS) + 1);
    }
}

int main(int argc, char **argv) {
    if (argc == 2 && !strcmp(argv[1], "glyphs")) {
        make_glyphs();
    } else if (argc == 2 && !strcmp(argv[1], "chr")) {
        make_chr_rom();
    } else {
        fprintf(stderr, "Usage: %s {chr|glyphs}\n", argv[0]);
        return 1;
    }
    return 0;
}
